"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class SomeEnum(_SomeEnum, metaclass=_SomeEnumEnumTypeWrapper):
    pass

class _SomeEnum:
    V = typing.NewType("V", builtins.int)

class _SomeEnumEnumTypeWrapper(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SomeEnum.V],
    builtins.type,
):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    UNKNOWN = SomeEnum.V(0)
    ONE = SomeEnum.V(1)
    TWO = SomeEnum.V(2)

UNKNOWN = SomeEnum.V(0)
ONE = SomeEnum.V(1)
TWO = SomeEnum.V(2)
global___SomeEnum = SomeEnum

class DummyMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ONE_FIELD_NUMBER: builtins.int
    THING_FIELD_NUMBER: builtins.int
    SOMETHING_FIELD_NUMBER: builtins.int
    ELSE_FIELD_NUMBER: builtins.int
    one: builtins.int = ...
    thing: builtins.int = ...
    something: builtins.int = ...
    def __init__(
        self,
        *,
        one: builtins.int = ...,
        thing: builtins.int = ...,
        something: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "else", b"else", "one", b"one", "something", b"something", "thing", b"thing"
        ],
    ) -> None: ...

global___DummyMessage = DummyMessage
