# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from example.mod.v1 import another_pb2 as example_dot_mod_dot_v1_dot_another__pb2


class DummyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Dummy = channel.unary_unary(
            "/example.mod.v1.DummyService/Dummy",
            request_serializer=example_dot_mod_dot_v1_dot_another__pb2.DummyMessage.SerializeToString,
            response_deserializer=example_dot_mod_dot_v1_dot_another__pb2.DummyMessage.FromString,
        )


class DummyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Dummy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DummyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Dummy": grpc.unary_unary_rpc_method_handler(
            servicer.Dummy,
            request_deserializer=example_dot_mod_dot_v1_dot_another__pb2.DummyMessage.FromString,
            response_serializer=example_dot_mod_dot_v1_dot_another__pb2.DummyMessage.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "example.mod.v1.DummyService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class DummyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Dummy(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/example.mod.v1.DummyService/Dummy",
            example_dot_mod_dot_v1_dot_another__pb2.DummyMessage.SerializeToString,
            example_dot_mod_dot_v1_dot_another__pb2.DummyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
