# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/mod/v1/hyphen-ated.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="example/mod/v1/hyphen-ated.proto",
    package="example.mod.v1",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n example/mod/v1/hyphen-ated.proto\x12\x0e\x65xample.mod.v1"\x1c\n\x0c\x45xtraMessage\x12\x0c\n\x04text\x18\x01 \x01(\tb\x06proto3',
)


_EXTRAMESSAGE = _descriptor.Descriptor(
    name="ExtraMessage",
    full_name="example.mod.v1.ExtraMessage",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="text",
            full_name="example.mod.v1.ExtraMessage.text",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=52,
    serialized_end=80,
)

DESCRIPTOR.message_types_by_name["ExtraMessage"] = _EXTRAMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExtraMessage = _reflection.GeneratedProtocolMessageType(
    "ExtraMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _EXTRAMESSAGE,
        "__module__": "example.mod.v1.hyphen_ated_pb2"
        # @@protoc_insertion_point(class_scope:example.mod.v1.ExtraMessage)
    },
)
_sym_db.RegisterMessage(ExtraMessage)


# @@protoc_insertion_point(module_scope)
