# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/mod/v1/referencing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

from example.mod.v1 import another_pb2 as example_dot_mod_dot_v1_dot_another__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="example/mod/v1/referencing.proto",
    package="example.mod.v1",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n example/mod/v1/referencing.proto\x12\x0e\x65xample.mod.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1c\x65xample/mod/v1/another.proto"i\n\x12ReferencingMessage\x12&\n\x02ts\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x05\x64ummy\x18\x02 \x01(\x0b\x32\x1c.example.mod.v1.DummyMessageb\x06proto3',
    dependencies=[
        google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,
        example_dot_mod_dot_v1_dot_another__pb2.DESCRIPTOR,
    ],
)


_REFERENCINGMESSAGE = _descriptor.Descriptor(
    name="ReferencingMessage",
    full_name="example.mod.v1.ReferencingMessage",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="ts",
            full_name="example.mod.v1.ReferencingMessage.ts",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="dummy",
            full_name="example.mod.v1.ReferencingMessage.dummy",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=115,
    serialized_end=220,
)

_REFERENCINGMESSAGE.fields_by_name[
    "ts"
].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_REFERENCINGMESSAGE.fields_by_name[
    "dummy"
].message_type = example_dot_mod_dot_v1_dot_another__pb2._DUMMYMESSAGE
DESCRIPTOR.message_types_by_name["ReferencingMessage"] = _REFERENCINGMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReferencingMessage = _reflection.GeneratedProtocolMessageType(
    "ReferencingMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _REFERENCINGMESSAGE,
        "__module__": "example.mod.v1.referencing_pb2"
        # @@protoc_insertion_point(class_scope:example.mod.v1.ReferencingMessage)
    },
)
_sym_db.RegisterMessage(ReferencingMessage)


# @@protoc_insertion_point(module_scope)
