"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import example.mod.v1.another_pb2
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class ReferencingMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TS_FIELD_NUMBER: builtins.int
    DUMMY_FIELD_NUMBER: builtins.int
    @property
    def ts(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def dummy(self) -> example.mod.v1.another_pb2.DummyMessage: ...
    def __init__(
        self,
        *,
        ts: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        dummy: typing.Optional[example.mod.v1.another_pb2.DummyMessage] = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["dummy", b"dummy", "ts", b"ts"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["dummy", b"dummy", "ts", b"ts"]
    ) -> None: ...

global___ReferencingMessage = ReferencingMessage
